services:
  solr:
    container_name: solr_pri

    image: solr:9.7

    ports:
     - "8983:8983"

    volumes:
      - solr_data:/data

    command:
      - solr-precreate
      - courses

volumes:
  solr_data:
    driver: local
    driver_opts:
      type: none
      device: data
      o: bind